= Example Docs for Skinning Purposes
Author Name
:idprefix:
:idseparator: -
:!example-caption:
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2
:page-supergroup-scala-java: Language
:page-supergroup-sbt-maven: Build Tool
:page-supergroup-sbt-maven-gradle: Build Tool
:page-supergroup-minishift-minikube: Platform
:page-supergroup-kubernetes-openshift: Platform
:page-supergroup-mac-ubuntu: OS


== Suspendisse tincidunt varius velit

Aenean vitae orci ut lorem semper auctor vitae at ex. Fusce lobortis magna mauris, sit amet cursus erat iaculis vel. Aenean eget lacus vel nibh suscipit pharetra. Nunc facilisis turpis ut leo tincidunt luctus. In sit amet odio sit amet purus convallis vulputate. Curabitur laoreet et lacus in ornare.

Donec volutpat sed tellus non gravida. Maecenas quis ornare est, vel convallis turpis. In at congue lacus. In eu suscipit magna, nec maximus odio. Aenean vitae orci ut lorem semper auctor vitae at ex. Fusce lobortis magna mauris, sit amet cursus erat iaculis vel. Aenean eget lacus vel nibh suscipit pharetra.

== Formatted Text
See: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#formatted-text[window=_blank]

== Hello

link:https://www.youtube.com/watch?v=-9pVwCkkE1I[Watch on YouTube ,role=yt-widget]

----
bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained
----

bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained


== Images

----
image::https://d3gnpvjw8j16uq.cloudfront.net/assets/images/svg/diagrams/lightbend-platform-overview.svg[Lightbend Platform Overview]
----

image::https://d3gnpvjw8j16uq.cloudfront.net/assets/images/svg/diagrams/lightbend-platform-overview.svg[Lightbend Platform Overview]


== Block Image Groups

=== Basic example
Images are vertically centered by default. Images will proportionately take up horizontal space based on their natural widths. On small screens the images will resort back to stacking in a column down the page.

----
[.image-group]
--
image::https://via.placeholder.com/600x150[]
image::https://via.placeholder.com/300x500[]
image::https://via.placeholder.com/500x300[]
--
----

[.image-group]
--
image::https://via.placeholder.com/600x150?text=Example+Image[]
image::https://via.placeholder.com/300x500?text=Example+Image[]
image::https://via.placeholder.com/500x300?text=Example+Image[]
--

{empty} +

=== Vertically align to top

  
----
[.image-group.top]
--
image::https://via.placeholder.com/300x300[]
image::https://via.placeholder.com/300x600[]
image::https://via.placeholder.com/300x400[]
image::https://via.placeholder.com/300x600[]
image::https://via.placeholder.com/300x300[]
image::https://via.placeholder.com/300x200[]
--
----

[.image-group.top]
--
image::https://via.placeholder.com/300x300?text=Example+Image[]
image::https://via.placeholder.com/300x600?text=Example+Image[]
image::https://via.placeholder.com/300x400?text=Example+Image[]
image::https://via.placeholder.com/300x600?text=Example+Image[]
image::https://via.placeholder.com/300x300?text=Example+Image[]
image::https://via.placeholder.com/300x200?text=Example+Image[]
--

{empty} +

=== Vertically align to bottom

----
[.image-group.bottom]
--
image::https://via.placeholder.com/600x150[]
image::https://via.placeholder.com/300x500[]
image::https://via.placeholder.com/500x300[]
--
----

[.image-group.bottom]
--
image::https://via.placeholder.com/600x150?text=Example+Image[]
image::https://via.placeholder.com/300x500?text=Example+Image[]
image::https://via.placeholder.com/500x300?text=Example+Image[]
--

{empty} +

=== Custom Widths

----
[.image-group]
--
[.width-25]
image::https://via.placeholder.com/600x300[]
[.width-50]
image::https://via.placeholder.com/600x300[]
[.width-25]
image::https://via.placeholder.com/600x300[]
--
----

[.image-group]
--
[.width-25]
image::https://via.placeholder.com/600x300?text=25%+Width[]
[.width-50]
image::https://via.placeholder.com/600x300?text=50%+Width[]
[.width-25]
image::https://via.placeholder.com/600x300?text=25%+Width[]
--

{empty} +

You can use the following widths
----
[.width-5] 
[.width-10] 
[.width-15] 
[.width-20] 
[.width-25] 
[.width-30] 
[.width-35] 
[.width-40] 
[.width-45] 
[.width-50] 
[.width-55] 
[.width-60] 
[.width-65] 
[.width-70] 
[.width-75] 
[.width-80] 
[.width-85] 
[.width-90] 
[.width-95] 
[.width-100]
----


== Tabsets

[.tabset] 
Scala::
This is the scala of the first tab.
Java::
+
[source,java]
----
public class Minikube {
  private String name;
  public Person(String name) {
    this.name = name;
  }
}
----


[.tabset] 
Play::
+ 
-- 
This is the content of the first tab.

Another paragraph in the first tab.

[source,xml]
----
$ a code block
----
--

Akka::
+
--
This is the content of the second tab.

[source,java]
----
$ a code block
----
--

Lagom::
+
--
This is the content of the second tab.

[source,console]
----
$ a code block
----
--



[.tabset] 
Scala::
+ 
-- 
This is the content of the first tab.

Another paragraph in the first tab.

[source,console]
----
$ a code block
----
--

Java::
+
--
This is the content of the second tab.

[source,console]
----
$ a code block
----
--


[.tabset] 
Minikube::
+ 
-- 
This is the hello of the first tab.

Another paragraph in the first tab.

[source,console]
----
$ a code block
----
--

Minishift::
+
--
This is the java of the second tab.

[source,json]
----
{
  "name": "module-name",
  "version": "10.0.1",
  "description": "An example module to illustrate the usage of package.json",
  "author": "Author Name <author@example.com>",
  "scripts": {
    "test": "mocha",
    "lint": "eslint"
  }
}
----
--

== Table Examples


|===
|Title | Description

| Introducing Lightbend Platform
| Describes the benefits of using Lightbend Platform and the business use cases that it supports. Read xref:streaming-architecture.adoc[From batch to streaming - the power of Lightbend Pipelines] to get an overview of why streaming has become critical for processing data and how Lightbend Pipelines enables rapid development and deployment. xref:traditional-architecture.adoc[Limitations of traditional architectures] shows how reactive microservices can help you successfully meet the challenges of digital transformation and taking advantage of cloud computing.

| Before you start: design and planning
| For those new to Reactive microservices, streaming, or Kubernetes-based platforms, this section contains fundamental information to help you get the most out of your efforts. Read xref:microservices-project.adoc[Planning a microservices project] to start with the Lightbend Platform tool that best fits your team and requirements. xref:streaming-and-analysis.adoc[Planning for streaming data and analysis] lists some important factors to keep in mind when working with streaming data. xref:planning-a-cluster.adoc[Deployment platform recommendations] provides an overview of Kubernetes-based platforms and provides tips and guidelines that will help when setting up environments for development and testing or for production.

| Getting started
| Describes how to obtain a Lightbend Platform subscription and explains support terminology. xref:preparing-dev-env.adoc[Preparing a development environment] shows you how to add the appropriate credentials to your build structure and how to set up a local Kubernetes cluster for testing. xref:setting-up-production-env.adoc[Setting up a production environment] provides helpful links and tips for setting up a multi-cluster Kubernetes-based production environment. xref:lightbend-platform.adoc[Lightbend Platform specifics] 

|=== 



[cols=2*,options="header"]
|===
|Name of Column 1
|Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===


|=== 

| Cell in column 1, row 1 | Cell in column 2, row 1  

| Cell in column 1, row 2 | Cell in column 2, row 2

| Cell in column 1, row 3 | Cell in column 2, row 3

|=== 


|===
|Name of Column 1 |Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===


[frame=topbot]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===


[frame=sides]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

[grid=rows]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

[grid=cols]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

[grid=none]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

[caption="Table A. "]
.A formal table
|===
|Name of Column 1 |Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===



[cols="3*"] 
|===
|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===



|===
|Source Code 1 |Source Code 2

a|
[source,python]
----
import os
print "%s" %(os.uname())
----

a|
[source,python]
----
import os
print ("%s" %(os.uname()))
----
|===


[.scala] 
Used to enter text or control items on the screen.
[.java]
Used to enter text or control items on the screen.

[.group-language]
--

term 1::
This description needs two paragraphs.
To attach them both to term 1, use a list continuation (+) on the line separating the paragraphs.
+
This is the second paragraph for term 1.

term 2:: This description includes an admonition block.
Like additional paragraphs, blocks also need to be connected with a +.
+
NOTE: An admonition block that is part of term 2's description.

term 3::
* unordered list item
.. ordered list item
... another ordered list item

--




[source,json]
----
{
  "name": "module-name",
  "version": "10.0.1",
  "description": "An example module to illustrate the usage of package.json",
  "author": "Author Name <author@example.com>",
  "scripts": {
    "test": "mocha",
    "lint": "eslint"
  }
}
----

.Example paragraph syntax
[source,asciidoc]
----
.Optional title
[example]
This is an example paragraph.
----

.Optional title
[example]
This is an example paragraph.

How about some code?

[source,js]
----
vfs
  .src('js/vendor/*.js', { cwd: 'src', cwdbase: true, read: false })
  .pipe(tap((file) => { // <1>
    file.contents = browserify(file.relative, { basedir: 'src', detectGlobals: false }).bundle()
  }))
  .pipe(buffer())
  .pipe(uglify())
  .pipe(gulp.dest('build'))
----
<1> The tap function is used to wiretap the data in the pipe.

Cum dicat #putant# ne.
Est in <<inline,reque>> homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

....
pom.xml
src/
  main/
    java/
      HelloWorld.java
  test/
    java/
      HelloWorldTest.java
....

Select menu:File[Open Project] to open the project in your IDE.
Per ea btn:[Cancel] inimicus.
Ferri kbd:[F11] tacimates constituam sed ex, eu mea munere vituperata kbd:[Ctrl,T] constituam.

.Sidebar
****
Platonem complectitur mediocritatem ea eos.
Ei nonumy deseruisse ius.
Mel id omnes verear.

Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.
****

=== Liber recusabo

No sea, at invenire voluptaria mnesarchum has.
Ex nam suas nemore dignissim, vel apeirian democritum et.
At ornatus splendide sed, phaedrum omittantur usu an, vix an noster voluptatibus.

****
[TIP]
This oughta do it!

Platonem complectitur mediocritatem ea eos.
Ei nonumy deseruisse ius.
Mel id omnes verear.

Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.
****



No sea, at invenire voluptaria mnesarchum has.
Ex nam suas nemore dignissim, vel apeirian democritum et.
At ornatus splendide sed, phaedrum omittantur usu an, vix an noster voluptatibus.

. potenti donec cubilia tincidunt
. etiam pulvinar inceptos velit quisque aptent himenaeos
. lacus volutpat semper porttitor aliquet ornare primis nulla enim

Natum facilisis theophrastus an duo.
No sea, at invenire voluptaria mnesarchum has.

* ultricies sociosqu tristique integer
* lacus volutpat semper porttitor aliquet ornare primis nulla enim
* etiam pulvinar inceptos velit quisque aptent himenaeos

Eu sed antiopam gloriatur.
Ea mea agam graeci philosophia.

* [ ] todo
* [x] done!

Vis veri graeci legimus ad.

sed::
splendide sed

mea::
agam graeci

At ornatus splendide sed.

[#dependencies%autowidth]
|===
|Library |Version

|eslint
|^1.7.3

|eslint-config-gulp
|^2.0.0

|expect
|^1.20.2

|istanbul
|^0.4.3

|istanbul-coveralls
|^1.0.3

|jscs
|^2.3.5
|===

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[NOTE]
====
You've been down _this_ road before.
====

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[WARNING]
====
Watch out!
====

[CAUTION]
====
[#inline]#I wouldn't try that if I were you.#
====

[IMPORTANT]
====
Don't forget this step!
====

.Key Points to Remember
[TIP]
====
If you installed the CLI and the default site generator globally, you can upgrade both of them with the same command.

 $ npm i -g @antora/cli @antora/site-generator-default
====



Crawling through the twisted understory...
Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.
Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

=== A Recipe for Potion

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.
Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

==== Searching for Burdockian

Crawling through the twisted understory...

==== Searching for Burdockian

Crawling through the twisted understory...

==== Searching for Burdockian

Crawling through the twisted understory...
Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.
Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.

[TIP]
This oughta do it!

Cum dicat putant ne.
Est in reque homero principes, meis deleniti mediocrem ad has.
Altera atomorum his ex, has cu elitr melius propriae.
Eos suscipit scaevola at.




The Shopping Cart example is already configured to run. In this section, we want to point your attention to the necessary pieces that you would need to provide for your own application. Preparation for production includes:

* Creating a production configuration file for the Shopping Cart microservice
* Defining a deployment spec for OpenShift

The production configuration of Lagom and the deployment spec are tightly coupled; many items in the two files correspond. Rather than document the two types of configuration separately, this guide interweaves them, making it easier to understand the relationships between them.

The sample app includes the complete configuration file and deployment spec in their final form. This guide includes just snippets to show you the most relevant configuration. In this guide, we'll review the most details for the `shopping-cart` microservice. The `inventory` microservice is trivial, it doesn't talk to a database, it doesn't do any clustering, and everything it needs is a subset of what the `shopping-cart` microservice needs. You can refer to the sample app for the `inventory` microservice configuration.

:sectnums:
== View the configuration files

First, let's look at the production configuration file for the Shopping Cart microservice and a barebones OpenShift deployment spec:

.. From the example's `shopping-cart/src/main/resources` directory, open the file named `prod-application.conf`.
.. Notice the following contents:
+
[source,conf]
----
include "application" //<1>

play {
 server {
   pidfile.path = "/dev/null" //<2>
  }
}
----
+
<1> This line includes Shopping Cart's main `application.conf` file. Any subsequent configuration will override the configuration from `application.conf`. This pattern allows us to keep our main, non-specific configuration in `application.conf`, while keeping production-specific configuration separate.
+
<2> Setting `play.server.pidfile.path = /dev/null` https://www.playframework.com/documentation/2.7.x/ProductionConfiguration#Changing-the-path-of-RUNNING_PID[disables] the use of a `pidFile`. A `pidFile` is not necessary for a process running in a container.

.. Open the `shopping-cart.yaml` from the `deploy` directory.
.. Note the numbered items, which are explained below:
+
[source,yaml]
----
 apiVersion: "apps/v1"
 kind: Deployment #<1>
 metadata:
  name: shopping-cart
 spec:
  selector:
    matchLabels:
      app: shopping-cart #<2>

  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: "shopping-cart:latest" #<3>
          env:
            - name: JAVA_OPTS #<4>
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
          resources:
            limits:
              memory: 512Mi #<5>
            requests:
              cpu: 0.25 #<6>
              memory: 512Mi
 ---
 apiVersion: v1
 kind: Service
 metadata:
  name: shopping-cart
 spec:
  ports:
    - name: http
      port: 80 #<7>
      targetPort: 9000
  selector:
    app: shopping-cart
  type: LoadBalancer
----
+
<1> This line defines a Kubernetes `Deployment`, a logical grouping of pods that represent a single microservice using the same template. They support https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deploymentstrategy-v1-apps[configurable rolling updates], meaning that the deployment will be gradually upgraded, rather than upgrading every pod at once and incurring an outage.
<2> We label the pod in the `template` with `app: shopping-cart`. This must match the the deployment's `matchLabels` and also the `selector` in the Kubernetes Service configuration, so that the deployment knows which pods it owns and should maintain and upgrade, and so the Kubernetes Service knows which pods to include in its Service resolution.
<3> The image we're using is `shopping-cart:latest`. This corresponds to the name and version of the microservice in our build. We discuss how to select an appropriate version number below.
<4> We use the `JAVA_OPTS` environment variable to pass the configuration to tell Lagom to use the `prod-application.conf` configuration file, rather than the default `application.conf`.
<5> We've configured a maximum of 256mb of memory for the JVM heap size, while the container gets 512mb. The container gets more memory than the JVM heap because the JVM will consume other memory for: class file metadata, thread stacks, compiled code, and JVM specific libraries.
<6> We've only requested minimal CPU for the container. This is suitable for a local deployment, but you should increase it for real production deployments. Note that we also haven't set a CPU limit, this is because the Akka documentation https://doc.akka.io/docs/akka/2.5/additional/deploy.html#resource-limits[recommends that JVMs do not set a CPU limit].
<7> The Kubernetes Service exposes HTTP on port `80`, and directs it to port `9000` on the pods. Port `9000` is Lagom's default HTTP port.

****
TIP: Image version number

The deployment spec above uses an image version tag of `latest`. The `latest` tag does not automatically refer to the latest deployed version of an image, it simply is the default tag that is used when no tag is specified. We could have just used `shopping-cart`, and this would mean the same thing as `shopping-cart:latest`. For development, this is convenient.

For production, the use of the `latest` tag is considered bad practice. We recommend using actual version number, one that gets updated each time you deploy. In the Building Shopping Cart section of this guide we will describe how to configure your build to base its version number off the current `git` commit hash. This is especially convenient for continuous deployment scenarios, since a human doesn't need to be involved in selecting a unique version number. After building the image, you can take the version number generated in that step and update the image referenced in the spec accordingly.
****

== Add Play application secret

Play Framework requires a secret key which is used to sign its session cookie, a JSON Web Token. To do this, we'll generate a secret, store it in the Kubernetes Secret API, and then update our configuration and spec to consume it.


.. Generate the secret:
+
[source,sh]
include:::example$create-application-secret.sh[]

.. Note that the `prod-application.conf` file contains the logic to consume the secret via an environment variable:
+
```conf
play {
  http.secret.key = "${APPLICATION_SECRET}"
}
```

.. Note that the `shopping-cart.yaml` file also uses the secret:
+
```yaml
- name: APPLICATION_SECRET
  valueFrom:
    secretKeyRef:
        name: shopping-cart-application-secret
        key: secret
```

== View the configuration to connect to PostgreSQL

In Setting up PostgreSQL we described the requirements the sample app and this guide have for a PostgreSQL service, including the requirement for the service to be called `postgresql`, and for there to be a secret called `postgres-shopping-cart`. Now we need to check that Shopping Cart is configure to connect to that service and consume the secret.

.. In `prod-application.conf`, find the following configuration:
+
```conf
db.default {
    url = ${POSTGRESQL_URL}
    username = ${POSTGRESQL_USERNAME}
    password = ${POSTGRESQL_PASSWORD}
}

lagom.persistence.jdbc.create-tables.auto = false
```
+
This will override the defaults defined for development in `application.conf`. You can see that we've disabled the automatic creating of tables, since we've already created them.

.. The `shopping-cart.yaml` file also needs three environment variables: the URL, username, and password. The first is hard coded into the spec, and the second two we'll consume as secrets. Find the following lines to verify:
+
```yaml
- name: POSTGRESQL_URL
  value: "jdbc:postgresql://postgresql/shopping_cart"
- name: POSTGRESQL_USERNAME
  valueFrom:
    secretKeyRef:
        name: postgres-shopping-cart
        key: username
- name: POSTGRESQL_PASSWORD
  valueFrom:
    secretKeyRef:
        name: postgres-shopping-cart
        key: password
```
+
NOTE: If you used a different name for the PostgreSQL database deployment, or for the Kubernetes secrets, you'll need to update the spec accordingly.

== View the configuration to connect to Kafka

In Setting up Kafka, we described the requirements for a Kafka instance. Lagom will automatically read an environment variable called `KAFKA_SERVICE_NAME` if present, so there's nothing to add in the Shopping Cart configuration file.

We just need `shopping-cart.yaml` to pass the environment variable, pointing to the Kafka service we provisioned. The actual service name that we need to configure needs to match the SRV lookup for the Kafka broker. Our Kafka broker defines a TCP port called `clients`. To lookup the IP address or host name and port number, we need to use a service name of `_clients._tcp.strimzi-kafka-brokers`.

Find the following lines in `shopping-cart.yaml`:

```yaml
- name: KAFKA_SERVICE_NAME
  value: "_clients._tcp.strimzi-kafka-brokers"
```

== Configure the service locator

Aenean vitae orci ut lorem semper auctor vitae at ex. Fusce lobortis magna mauris, sit amet cursus erat iaculis vel. Aenean eget lacus vel nibh suscipit pharetra. Nunc facilisis turpis ut leo tincidunt luctus. In sit amet odio sit amet purus convallis vulputate. Curabitur laoreet et lacus in ornare.

Donec volutpat sed tellus non gravida. Maecenas quis ornare est, vel convallis turpis. In at congue lacus. In eu suscipit magna, nec maximus odio. Aenean vitae orci ut lorem semper auctor vitae at ex. Fusce lobortis magna mauris, sit amet cursus erat iaculis vel. Aenean eget lacus vel nibh suscipit pharetra.

.. If using Maven, check the project `pom.xml` to make sure the value `scala.binary.version` is defined there and set to the value of `2.12`.

.. Check the `pom.xml` in each microservice implementation project or the declaration for each microservice implementation project in `build.sbt` to make sure the following dependency exists:
+
[cols="1,6a"]
|===
|Java with Maven
|[source,xml]
----
<dependency>
  <groupId>com.lightbend.lagom</groupId>
  <artifactId>lagom-javadsl-akka-discovery-service-locator_${scala.binary.version}</artifactId>
</dependency>
----

|Java with sbt
|[source,scala]
----
libraryDependencies +=
  "com.lightbend.lagom" %% "lagom-javadsl-akka-discovery-service-locator" % "1.5.1"
----
|Scala with sbt
|[source,scala]
----
libraryDependencies +=
  "com.lightbend.lagom" %% "lagom-scaladsl-akka-discovery-service-locator" % "1.5.1"
----
|===
